💚 Force upgrade of bash so sdkman will work
Before this change:

```
Looking for a previous installation of SDKMAN...
Checking Bash version...

======================================================================================================
 SDKMAN requires Bash 4 or higher, but you are running Bash 3.2.57(1)-release.

 Please upgrade Bash using your system's package manager.
 On macOS, you can install a modern Bash with Homebrew:

    $ brew install bash
======================================================================================================

'exit 1': command failed with exit code 1.
Error: Process completed with exit code 1.
```

After this change: build succeeds